---
title: "Visualization Homework"
output:
  pdf_document: default
  html_document: default
date: "2023-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readr")
library(ggplot2)
```

```{r}
acacia <- read.csv(file = "../data raw/ACACIA_DREPANOLOBIUM_SURVEY.txt",
         sep ="\t",
         na.strings = "dead")
is.numeric(acacia$HEIGHT)
head(acacia)
#View(acacia)
```

```{r}
trees <- read_tsv("../data raw/TREE_SURVEYS.txt")
  
```

```{r}
tail(trees$HEIGHT,500)
```

```{r}
str(trees)
trees$HEIGHT
trees$HEIGHT <- as.numeric(trees$HEIGHT)
head(trees)
```
$Alternative Way
```{r}
trees <- read_tsv("../data raw/TREE_SURVEYS.txt",
               col_types = list(HEIGHT = col_double(),
                                AXIS_2 = col_double()))
```

```{r}
trees$canopy_area <- trees$AXIS_1 * trees$AXIS_2
head(trees)
```

```{r}
numbers <- 1:10
numbers[c(1:3, 5:10)]
numbers[-4]
trees [1:3,-(5:10)]
```

```{r}
subset(trees, select =c (SURVEY, YEAR, SITE, canopy_area))
trees2 <- trees[,c("SURVEY", "YEAR", "SITE", "canopy_area")]
```

```{r}
ggplot(data = trees, mapping = aes(x = canopy_area, y = HEIGHT, color = TREATMENT)) + geom_point() + 
  labs (x = "Canopy area") + 
facet_wrap(~SPECIES)
```

```{r}
#or we can do this with teh subset function
trees3 <- subset(trees, canopy_area <=400)
# or finding the actual value that is the outlier
which(trees$canopy_area > 2000)
trees4 <- trees[-3839,]
```

```{r}
trees3 <- subset(trees, canopy_area <= 400)
ggplot(data = trees3, mapping = aes(x = canopy_area, y= HEIGHT, color = TREATMENT)) + geom_point() + facet_wrap(~SPECIES)
```
Exercise 4
```{r}
ggplot() +
geom_point(data = trees,
mapping = aes(x = CIRC , y = HEIGHT), color = "gray") + geom_smooth(data = trees,
mapping = aes(x = CIRC , y = HEIGHT), color = "gray") + geom_point(data = acacia,
mapping = aes(x = CIRC , y = HEIGHT ), color = "red") + geom_smooth(data = acacia,
mapping = aes(x = CIRC , y = HEIGHT ), color = "red") + scale_x_log10() +scale_y_log10() + geom_smooth(method = "lm")
labs(x = "Circumference (cm)", y = "Height (m)", title = "Circumference to the Height Relationship of Acacia")
```
# Exercise 4 - Making the scatterplot in class

```{r}
acacia <- read.csv(file = "../data raw/ACACIA_DREPANOLOBIUM_SURVEY.txt",
         sep ="\t",
         na.strings = "dead")
is.numeric(acacia$HEIGHT)

trees <- read_tsv("../data raw/TREE_SURVEYS.txt",
               col_types = list(HEIGHT = col_double(),
                                AXIS_2 = col_double()))
```
Visual Quality assurance and control with the function str()
```{r}
str(acacia)
is.numeric(acacia$CIRC)
is.numeric(acacia$HEIGHT)
```
```{r}
str(trees)
is.numeric(trees$CIRC)
is.numeric(trees$HEIGHT)
```
```{r}
ggplot() +
  geom_point(data = trees, mapping = aes(x= CIRC, y= HEIGHT), color = "gray", alpha = 0.5) + 
  geom_point(data = acacia, mapping =aes (x = AXIS1, y=AXIS2), color = "red", alpha = 0.6)
```
```{r}
ggplot(data = trees, mapping = aes(x= CIRC, y= HEIGHT), color = "gray", alpha = 0.5) + 
  geom_point( color = "gray") +
  geom_point(data = acacia, mapping =aes (x = CIRC, y=HEIGHT), color = "red", alpha = 0.6) +
    scale_x_log10() +
    scale_y_log10() +
    geom_smooth(method = "lm") +
    geom_smooth(data = acacia, mapping = aes(x= CIRC, y= HEIGHT), method = "lm")
    
    
    
```
