---
title: "visualization-uhuru-day2.Rmd"
output: pdf_document
date: "2023-02-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r eval = TRUE}
read.csv(file = "../data raw/ACACIA_DREPANOLOBIUM_SURVEY.txt", sep = "\t")
```

```{r eval = TRUE}
acacia <- read.csv(file = "../data raw/ACACIA_DREPANOLOBIUM_SURVEY.txt", sep = "\t")
```

#Rescaling Axes
```{r}
ggplot(data = acacia, mapping = aes(x = CIRC, y = HEIGHT)) +
geom_point(size = 3, color = "blue", alpha = 0.5) +
scale_y_log10() +
scale_x_log10()
```

#Fitting Linear Models
```{r}
ggplot(acacia, aes(x = CIRC, y = HEIGHT, color = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth()

ggplot(acacia, aes(x = CIRC, y = HEIGHT, color = TREATMENT, linetype = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth()


ggplot(acacia, aes(x = CIRC, y = HEIGHT, color = TREATMENT)) +
geom_point(size = 3, alpha = 0.5) +
geom_smooth(method = "lm") # try with "glm"
```

#Histograms and Bar plots
```{r}
ggplot(data = acacia, mapping = aes(x = TREATMENT)) +
geom_bar()

ggplot(acacia, aes(x = CIRC)) +
geom_histogram(fill = "red")

ggplot(acacia, aes(x = CIRC, color = TREATMENT)) +
geom_histogram(bins = 20)

ggplot(acacia, aes(x = CIRC, fill = TREATMENT)) +
geom_histogram(bins = 20, color = "gray")
```

#Layering Data

```{r}
ggplot() +
geom_point(data = acacia,
           mapping = aes(x = CIRC, y = HEIGHT,
                         color = TREATMENT)) +
geom_smooth(data = acacia,
            mapping = aes(x = CIRC, y = HEIGHT))
ggplot() +
geom_point(data = acacia,
           mapping = aes(x = CIRC, y = HEIGHT,
                         color = TREATMENT)) +
geom_smooth(data = acacia,
            mapping = aes(x = CIRC, y = HEIGHT)) +
geom_histogram(data = acacia,
               mapping = aes(x = CIRC, color = TREATMENT),
               alpha = 0.1)

```

#Saving plots as image files
```{r}
ggsave("acacia_by_treatment.jpg")
ggsave("acacia_by_treatment.pdf", height = 5, width = 5)

```

hi